	#Configure properties related to additional drop perks here. Drop chances can be modified in the SERVER config.
	[common.additional_drops]
		#If true, enables additional crop drops for hoes. True by default.
		enableAdditionalCropDrops = true
		#If true, enables additional ore drops for pickaxes. Pickaxes with Silk Touch remain unaffected. True by default.
		enableAdditionalOreDrops = true
		#If true, enables additional mob drops for swords. True by default.
		enableAdditionalMobDrops = true
