#Where to place mods button on main menu screen. Select "NO_CHANGE" to prevent any changes to the screen, useful for mod compatibility.
#Allowed Values: REPLACE_REALMS, LEFT_TO_REALMS, RIGHT_TO_REALMS, INSERT_BELOW_REALMS, NONE, NO_CHANGE
main_menu_mods_button = "INSERT_BELOW_REALMS"
#Show a small green orb indicating that mod updates are available.
update_notification = false
#Add mod count to mods button.
mod_count = true
#Force a dirt background to show for the mod list screen, even when inside of a world where it would normally be transparent.
force_dirt_background = true
#Where to place mods button on pause menu screen.
#Allowed Values: REPLACE_FEEDBACK, REPLACE_BUGS, REPLACE_FEEDBACK_AND_BUGS, REPLACE_AND_MOVE_LAN, INSERT_AND_MOVE_LAN, INSERT_BELOW_FEEDBACK_AND_BUGS, NONE
pause_screen_mods_button = "INSERT_BELOW_FEEDBACK_AND_BUGS"

