
#Embeddium Extra Settings
[Settings]

	[Settings.Misc]
		"Chunk Fade In Quality (OFF, FAST, FANCY)" = "FANCY"
		#Tweak JEI rendering so that the item list does not display unless search is active. This de-clutters the screen significantly unless you're actively using JEI.
		"Hide JEI Items" = false

	[Settings."FPS Counter"]
		"Display FPS Counter (OFF, SIMPLE, ADVANCED)" = "ADVANCED"
		"Right-align FPS Counter" = false
		"FPS Counter Distance" = 12

	[Settings."Entity Distance"]
		"Enable Max Distance Checks" = true
		"(TileEntity) Max Horizontal Render Distance [Squared, Default 64^2]" = 4096
		"(TileEntity) Max Vertical Render Distance [Raw, Default 32]" = 32
		"(Entity) Max Horizontal Render Distance [Squared, Default 64^2]" = 4096
		"(Entity) Max Vertical Render Distance [Raw, Default 32]" = 32

	[Settings.Zoom]
		"Lower Zoom Sensitivity" = true
		"Zoom Scrolling Enabled" = true
		"Zoom Transition Mode (OFF, LINEAR, SMOOTH)" = "SMOOTH"
		"Zoom Transition Mode (TOGGLE, HOLD, PERSISTENT)" = "HOLD"
		"Cinematic Camera Mode (OFF, VANILLA, MULTIPLIED)" = "OFF"
		"Enable Zoom Overlay" = true

	[Settings."Entity List"]
		"entities which should always be rendered" = ["minecraft:ender_dragon", "minecraft:ghast", "alexsmobs:void_worm", "alexsmobs:void_worm_part", "minecraft:wither", "twilightforest:naga", "twilightforest:lich", "twilightforest:yeti", "twilightforest:snow_queen", "twilightforest:minoshroom", "twilightforest:hydra", "twilightforest:knight_phantom", "twilightforest:ur_ghast", "atum:pharaoh", "mowziesmobs:barako", "mowziesmobs:ferrous_wroughtnaut", "mowziesmobs:frostmaw", "aoa3:skeletron", "aoa3:smash", "aoa3:baroness", "aoa3:clunkhead", "aoa3:corallus", "aoa3:cotton_candor", "aoa3:craexxeus", "aoa3:xxeus", "aoa3:creep", "aoa3:crystocore", "aoa3:dracyon", "aoa3:graw", "aoa3:gyro", "aoa3:hive_king", "aoa3:kajaros", "aoa3:miskel", "aoa3:harkos", "aoa3:raxxan", "aoa3:okazor", "aoa3:king_bambambam", "aoa3:king_shroomus", "aoa3:kror", "aoa3:mechbot", "aoa3:nethengeic_wither", "aoa3:red_guardian", "aoa3:blue_guardian", "aoa3:green_guardian", "aoa3:yellow_guardian", "aoa3:rock_rider", "aoa3:shadowlord", "aoa3:tyrosaur", "aoa3:vinecorne", "aoa3:visualent", "aoa3:voxxulon", "aoa3:bane", "aoa3:elusive", "gaiadimension:malachite_drone", "gaiadimension:malachite_guard", "blue_skies:alchemist", "blue_skies:arachnarch", "blue_skies:starlit_crusher", "blue_skies:summoner", "stalwart_dungeons:awful_ghast", "stalwart_dungeons:nether_keeper", "stalwart_dungeons:shelterer_without_armor", "dungeonsmod:extrapart", "dungeonsmod:king", "dungeonsmod:deserted", "dungeonsmod:crawler", "dungeonsmod:ironslime", "dungeonsmod:kraken", "dungeonsmod:voidmaster", "dungeonsmod:lordskeleton", "dungeonsmod:winterhunter", "dungeonsmod:sun", "forestcraft:beequeen", "forestcraft:iguana_king", "forestcraft:cosmic_fiend", "forestcraft:nether_scourge", "cataclysm:ender_golem", "cataclysm:ender_guardian", "cataclysm:ignis", "cataclysm:ignited_revenant", "cataclysm:netherite_monstrosity", "iceandfire:fire_dragon", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "iceandfire:dragon_multipart", "alexsmobs:spectre", "mowziesmobs:naga"]
		"modid(entities of this mod will always be rendered)" = ["witherstormmod"]
		"tile entities which should always be rendered" = ["minecraft:beacon"]
		"modid(tile entities of this mod will always be rendered)" = []

