
#GoalOptimizer
[Sheep]
	sheepHasEatGrassGoal = true
	sheepHasSwimGoal = true
	sheepHasPanicGoal = true
	sheepHasBreedGoal = true
	sheepHasTemptGoal = true
	sheepHasFollowParentGoal = true
	sheepHasWaterAvoidingRandomWalkingGoal = true
	sheepHasLookAtGoal = true
	sheepHasLookRandomlyGoal = true

[Pig]
	pigHasSwimGoal = true
	pigHasPanicGoal = true
	pigHasBreedGoal = true
	pigHasTemptGoalOfCarrotOnAStick = true
	pigHasTemptGoalOnFood = true
	pigHasFollowParentGoal = true
	pigHasWaterAvoidingRandomWalingGoal = true
	pigHasLookAtGoal = true
	pigHasLookRandomlyGoal = true

[Cow]
	cowHasSwimGoal = true
	cowHasPanicGoal = true
	cowHasBreedGoal = true
	cowHasTemptGoal = true
	cowHasFollowParentGoal = true
	cowHasWaterAvoidingRandomWalkingGoal = true
	cowHasLookAtGoal = true
	cowHasLookRandomlyGoal = true

[Fish]
	abstractFishHasPanicGoal = true
	abstractFishHasAvoidEntityGoal = true
	abstractFishHasSwimGoal = true
	abstractGroupFishHasFollowSchoolLeaderGoal = true
	pufferfishHasPufferGoal = true
	squidHasMoveRandomGoal = true
	squidHasFleeGoal = true

[Chicken]
	chickenHasSwimGoal = true
	chickenHasPanicGoal = true
	chickenHasBreedGoal = true
	chickenHasTemptGoal = true
	chickenHasFollowParentGoal = true
	chickenHasWaterAvoidingRandomWalkingGoal = true
	chickenHasLookAtGoal = true
	chickenHasLookRandomlyGoal = true

