
#Client Configuration
[client]

	[client.options]
		# If new item markers should be cleared when the inventory is closed.
		clear_on_close = true
		# If new item markers should be cleared when the item tooltip is displayed.
		clear_on_hover = true
		# If icons should match the color of items names (as shown in tooltips).  Otherwise icons will all be gold.
		item_name_color = false

