
#Magnesium/Rubidium Extra Settings
[Settings]

	[Settings.Misc]
		"Chunk Fade In Quality (OFF, FAST, FANCY)" = "FANCY"

	[Settings."FPS Counter"]
		"Display FPS Counter (OFF, SIMPLE, ADVANCED)" = "OFF"
		"Right-align FPS Counter" = false
		"FPS Counter Distance" = 12

	[Settings."Entity Distance"]
		"Enable Max Distance Checks" = true
		"(TileEntity) Max Horizontal Render Distance [Squared, Default 64^2]" = 4096
		"(TileEntity) Max Vertical Render Distance [Raw, Default 32]" = 32
		"(Entity) Max Horizontal Render Distance [Squared, Default 64^2]" = 4096
		"(Entity) Max Vertical Render Distance [Raw, Default 32]" = 32

	[Settings.Zoom]
		"Lower Zoom Sensitivity" = true
		"Zoom Scrolling Enabled" = true
		"Zoom Transition Mode (OFF, LINEAR, SMOOTH)" = "SMOOTH"
		"Zoom Transition Mode (TOGGLE, HOLD, PERSISTENT)" = "HOLD"
		"Cinematic Camera Mode (OFF, VANILLA, MULTIPLIED)" = "OFF"
		"Enable Zoom Overlay" = true

