
[client]
	#Toggles the lantern glow effect, which may look bad with certain shaders.
	glow_effect = true
	#Use the old Barakoa textures instead of the current ones.
	old_barakoa_textures = false
	#Enable camera shaking during certain mob attacks and abilities.
	do_camera_shake = true
	#Play boss battle themes during boss encounters.
	play_boss_music = true
	#Use custom player animations.
	custom_player_anims = true

