
#Opotato Common Config
["Opotato Settings"]
	"allow entities spawn limit" = false
	#Range: 1 ~ 100
	"max entities spawning number per chunk" = 10
	"entities whose spawn won't be limited" = ["modid:mobid"]
	"enable creative one pouch" = true

["Blue Skies Extra Settings"]
	"enable blue skies nerf" = true
	"allow every mod generate features in blue skies dimensions" = false
	#Range: > 6
	"gate keeper house spacing" = 18

["Ars Nouveau Extra Settings"]
	"disable mana gems generation in basic loot chests" = false

["Headshot Extra Settings"]
	"enable 'Ding' on Headshot" = true
	#Range: 0.0F ~ 1.0F. Type: Float
	#Range: 0.0 ~ 1.0
	"'Ding' volume" = 1.0
	#Range: 0.5F ~ 2.0F. Type: Float
	#Range: 0.0 ~ 1.0
	"'Ding' pitch" = 1.0

["Cracker's Wither Storm Mod Optimization Settings"]
	#Every settings here will improve performance a lot as the mod is really laggy
	"let wither sickness ticking system only take effect on players" = false
	"don't let the wither sickness ticking system affect monsters" = false
	"don't let the wither sickness ticking system affect animals" = false
	#With this turning on, the amount of block clusters will be reduced on rendering and they won't be rendered when no player see them
	"block cluster render optimization" = false
	#Entities that will be killed: Block Cluster, Sickened Skeleton, Sickened Creeper, Sickened Spider, Sickened Zombie, Tentacle, Withered Symbiont.
	#Inspired by Lag Removal mod.
	"kill witherstormmod entities after command block dies" = false
	#If this is turned on, a cache optimization will be applied to optimize the mod
	#If you summon multiple wither storms, they will be removed.
	"only one wither storm" = false

["L_Ender's Cataclysm Extra Settings"]
	"Ignitium Armor has damage" = false
	"Final Fractal has damage" = false
	"Infernal Forge has damage" = false
	"Monstrous Helm has damage" = false
	"Zweiender has damage" = false
	#Range: > 1
	"void core cool down, in ticks" = 120
	#Range: > 1
	"infernal forge cool down, in ticks" = 80
	#Range: > 1
	"incinerator cool down, in ticks" = 400
	#Range: > 5
	"soul black smith spacing" = 90
	#Range: > 5
	"soul black smith separation" = 70
	#Range: > 5
	"ruined citadel spacing" = 30
	#Range: > 5
	"ruined citadel separation" = 10
	#Range: > 5
	"burning arena spacing" = 112
	#Range: > 5
	"burning arena separation" = 70
	#Range: > 120
	"How long it takes to use Incinerator (charge) (in ticks)" = 72000
	#About enchantability factor, see enchantability in https://minecraft.fandom.com/wiki/Tiers.
	#Range: > 12
	"Incinerator's enchantability factor" = 16
	#Range: > 1
	"How many ticks will blazing brand effect caused by incinerator's flame strike ability exist on the attacked entities" = 200
	#Range: 1.0 ~ 3.4028235E38
	"How many damage will the flame strike caused by incinerator's ability give on the attacked entities" = 6.0
	#Range: 0.01 ~ 0.99
	"The incinerator's flame strike ability also does extra damages, which is a percentage of the attacked's max health, here it is" = 0.02

["The Undergarden Extra Settings"]
	#Range: > 5
	"catacomb spacing" = 24
	#Range: > 5
	"catacomb separation" = 8

