
["Sighted Configuration Settings"]
	#Mod enabled
	enabled = true
	#Do not load block entities (e.g. chests) in fake chunks.\nThese need updating every tick which can add up.\n\nEnabled by default because the render distance for block entities is usually smaller than the server-view distance anyway.
	noBlockEntities = true
	#Delays the unloading of chunks which are outside your view distance.
	#Saves you from having to reload all chunks when leaving the area for a short moment (e.g. cut scenes).
	#Does not work across dimensions.
	#Range: 1 ~ 3600
	unloadDelaySecs = 60
	#Changes the maximum value configurable for Render Distance.
	#
	# Requires Optifine
	#Range: 6 ~ 64
	maxRenderDistance = 32

