
#These options will be synced to joining clients.
[server]

	#Note: Base XP cost is based on the distance travelled.
	[server.baseXpCost]
		#Set to true if experience cost should be inverted, meaning the shorter the distance, the more expensive. Can be used to encourage other methods for short-distance travel.
		inverseXpCost = false
		#The amount of blocks per xp level requirement. If set to 500, the base xp cost for travelling 1000 blocks will be 2 levels.
		#Range: > 1
		blocksPerXPLevel = 1000
		#The minimum base xp cost
		#Range: 0.0 ~ Infinity
		minimumXpCost = 0.0
		#The maximum base xp cost (may be exceeded by multipliers defined below), set to 0 to disable all distance-based XP costs
		#Range: 0.0 ~ Infinity
		maximumXpCost = 0.0

	#These options apply to teleporting from one waystone to another by right-clicking it.
	[server.waystoneToWaystone]
		#The multiplier applied to the base xp cost when teleporting from one waystone to another.
		#Range: 0.0 ~ Infinity
		waystoneXpCostMultiplier = 1.0
		#The multiplier applied to the base xp cost when teleporting from one sharestone to another.
		#Range: 0.0 ~ Infinity
		sharestoneXpCostMultiplier = 1.0
		#The multiplier applied to the base xp cost when teleporting from a portstone.
		#Range: 0.0 ~ Infinity
		portstoneXpCostMultiplier = 0.0

	#These options apply to warp plates.
	[server.warpPlate]
		#The multiplier applied to the base xp cost when teleporting from one warp plate to another.
		#Range: 0.0 ~ Infinity
		warpPlateXpCostMultiplier = 0.0
		#The time in ticks that it takes to use a warp plate. This is the time the player has to stand on top for.
		#Range: > 0
		warpPlateUseTime = 20

	#These options apply to the optional Waystones button displayed in the inventory.
	[server.inventoryButton]
		#Set to 'NONE' for no inventory button. Set to 'NEAREST' for an inventory button that teleports to the nearest waystone. Set to 'ANY' for an inventory button that opens the waystone selection menu. Set to a waystone name for an inventory button that teleports to a specifically named waystone.
		inventoryButton = "NONE"
		#The multiplier applied to the base xp cost when teleporting via the inventory button.
		#Range: 0.0 ~ Infinity
		inventoryButtonXpCostMultiplier = 0.0
		#The cooldown between usages of the inventory button in seconds.
		#Range: > 0
		inventoryButtonCooldown = 300

	#These options apply to the global waystones.
	[server.globalWaystones]
		#The multiplier applied to the base xp cost when teleporting to a global waystone through any method.
		#Range: 0.0 ~ Infinity
		globalWaystonesXpCostMultiplier = 1.0
		#The multiplier applied to the cooldown when teleporting to a global waystone via inventory button or warp stone.
		#Range: 0.0 ~ Infinity
		globalWaystoneCooldownMultiplier = 1.0
		#Set to false to allow non-creative players to make waystones globally activated for all players.
		globalWaystoneRequiresCreative = true

	#These options apply to teleporting using the Warp Stone item.
	[server.warpStone]
		#The multiplier applied to the base xp cost when teleporting using a Warp Stone item (not the Waystone block, John)
		#Range: 0.0 ~ Infinity
		warpStoneXpCostMultiplier = 0.0
		#The cooldown between usages of the warp stone in seconds. This is bound to the player, not the item, so multiple warp stones share the same cooldown.
		#Range: > 0
		warpStoneCooldown = 300
		#The time in ticks that it takes to use a warp stone. This is the charge-up time when holding right-click.
		#Range: > 1
		warpStoneUseTime = 32

	#These options apply to teleporting using the scroll items.
	[server.scrolls]
		#The time in ticks it takes to use a scroll. This is the charge-up time when holding right-click.
		#Range: > 1
		scrollUseTime = 32

	#These options apply to teleporting between dimensions.
	[server.dimensionalWarp]
		#Set to 'ALLOW' to allow dimensional warp in general. Set to 'GLOBAL_ONLY' to restrict dimensional warp to global waystones. Set to 'DENY' to disallow all dimensional warps.
		#Allowed Values: ALLOW, GLOBAL_ONLY, DENY
		dimensionalWarp = "ALLOW"
		#The base xp level cost when travelling between dimensions. Ignores block distance.
		#Range: > 0
		dimensionalWarpXpCost = 3

	#These options apply to taking leashed mobs with you when teleporting.
	[server.leashedMobs]
		#If enabled, leashed mobs/animals will be teleported with you
		transportLeashed = true
		#Take animals with you when travelling between dimensions
		transportLeashedDimensional = true
		#How much xp is need per leashed animal to travel with you
		#Range: > 0
		costPerLeashed = 1
		#Which leashed mobs cannot be taken with you when travelling.
		leashedBlacklist = ["minecraft:wither"]

	#These options define restrictions when managing waystones.
	[server.restrictions]
		#If enabled, only the owner of a waystone (the one who placed it) can rename it.
		restrictRenameToOwner = false
		#If enabled, only creative players can place, edit or break waystones. This does NOT disable the crafting recipe.
		restrictToCreative = false
		#If enabled, waystones generated in worldgen are unbreakable.
		generatedWaystonesUnbreakable = false

