
["YUNG's Better Ocean Monuments"]

	###########################################################################################################
	## General settings.
	###########################################################################################################
	["YUNG's Better Ocean Monuments".General]
		# Whether or not vanilla ocean monuments should be disabled.
		# Default: true
		#
		"Disable Vanilla Ocean Monuments" = true

