#base size per serve
#Range: 1 ~ 100
baseServe = 4
#base nutrition factor
#Range: 0.0 ~ 100.0
baseNutrition = 0.1
#bonus for every extra food type
#Range: 0.0 ~ 100.0
varietyBonus = 0.2
#bonus for perfect food
#Range: 0.0 ~ 100.0
perfectionBonus = 0.5
#max number of ingredient entries
#Range: 1 ~ 20
maxIngredient = 9
#nourishment duration per food type
#Range: 1 ~ 10000
nourishmentDuration = 100

