# Please be aware that enabling any third-party mod integration introduces instability and performance overheads, caution is strongly advised.
# If crashes or issues arise, disable the related modules as the first step in troubleshooting and report the issue to Polymorph.
fastfurnace = true
fastsuite = true
fastbench = true

