#Horizontal offset of cycle slots display from default position.
#Allows for compatibility with mods that also add their own displays next to the hotbar.
#Range: > -2147483648
slots_x_offset = 0
#Vertical offset of cycle slots display from screen bottom.
#Allows for compatibility with mods that move the hotbar upwards such as the Raised mod (Raised has built-in support on Fabric).
#Range: > -2147483648
slots_y_offset = 0
#Cycle slots by pressing a hotbar key when the corresponding slot is already selected.
double_press_hotbar_key = true
#Modifier key required to be held to allow for scrolling through cycle slots.
#Setting to "NONE" will overwrite vanilla hotbar scrolling, making the hotbar only usable with keys.
#Allowed Values: DISABLED, NONE, CONTROL, SHIFT, ALT
scrolling_modifier_key = "ALT"
#Choose when the cycle slots display is shown next to the hotbar: Always, never, or only when the modifier key for scrolling is held. Doesn't disable cycling itself though.
#Allowed Values: ALWAYS, KEY, NEVER
slots_display_state = "ALWAYS"

