#Range on xz plane trading post should search for merchants.
#Range: 1 ~ 96
horizontal_range = 24
#Disable traders on the trading screen when they wander out of range.
enforce_range = false
#Teleport xp from trading from villagers on top of the trading post.
teleport_xp = true
#Range on y axis trading post should search for merchants.
#Range: 1 ~ 96
vertical_range = 16
#Trader entities disabled from being found by the trading post.
#Modders may add their own incompatible trader entities via the "tradingpost:blacklisted_traders" entity tag.
#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color.
trader_blacklist = []
#Close trading post interface when all traders have become unavailable.
close_empty_screen = true

