placeSnowInBlock = true
placeSnowInBlockNaturally = true
snowGravity = true
snowAlwaysReplaceable = true
snowAccumulationDuringSnowstorm = true
snowAccumulationDuringSnowfall = false
snowAccumulationMaxLayers = 8
thinnerBoundingBox = true
snowMakingIce = true
snowNeverMelt = false
snowAndIceMeltInWarmBiomes = false
snowNaturalMelt = true
snowReduceFallDamage = true
replaceWorldFeature = true
sustainGrassIfLayerMoreThanOne = true
retainOriginalBlocks = true
advancedBlockInteraction = true
sneakSnowball = true
mobSpawningMaxLayers = 8

[integration]
accumulationWinterOnly = false
