
["YUNG's Better Dungeons"]

	###########################################################################################################
	## General settings.
	###########################################################################################################
	["YUNG's Better Dungeons".General]
		# Whether or not dungeons should be allowed to place skeleton skulls and other mob heads.
		# This option may be useful for some modpack creators.
		# Default: true
		#
		"Enable Skulls & Heads" = true
		# Some dungeons can rarely spawn Nether-related blocks such as soul sand, soul campfires, and soul lanterns.
		# Note that the blocks will be purely decorative - nothing progression-breaking like Ancient Debris.
		# Set this to false to prevent any Nether-related blocks from spawning in dungeons.
		# This option may be useful for some modpack creators.
		# Default: true
		#
		"Enable Nether Blocks in Dungeons" = true

	###########################################################################################################
	## Zombie Dungeon settings.
	###########################################################################################################
	["YUNG's Better Dungeons"."Zombie Dungeons"]
		# The longest distance that can be checked when attempting to generate a surface entrance staircase.
		# Making this too large may cause problems.
		# Default: 20
		#
		"Zombie Dungeon Surface Entrance Staircase Max Length" = 20

	###########################################################################################################
	## Small Dungeon settings.
	###########################################################################################################
	["YUNG's Better Dungeons"."Small Dungeons"]
		# The maximum number of banners that can spawn in a single small dungeon.
		# Default: 2
		#Range: 0 ~ 8
		"Small Dungeon Max Banner Count" = 2
		# The minimum number of chests that are guaranteed to spawn in a single small dungeon.
		# Default: 1
		"Small Dungeon Min Chest Count" = 1
		# The maximum number of chests that can spawn in a single small dungeon.
		# Default: 2
		"Small Dungeon Max Chest Count" = 2
		# Whether or not Small Dungeons can rarely place ore blocks in the corners of the dungeon.
		# If this is set to false, any ore blocks that spawn as part of a corner prop will instead be replaced with air.
		# Default: true
		#
		"Allow Ore Blocks in Corners" = true

	###########################################################################################################
	## Small Nether Dungeon settings.
	## These are disabled by default.
	###########################################################################################################
	["YUNG's Better Dungeons"."Small Nether Dungeons"]
		# Whether or not small Nether dungeons should spawn.
		# Default: false
		"Enable Small Nether Dungeons" = false
		# Whether or not Wither skeletons spawned from small Nether dungeons have a chance to drop Wither skeleton skulls.
		# Default: true
		"Wither Skeletons From Spawners Drop Wither Skeleton Skulls" = true
		# Whether or not blazes spawned from small Nether dungeons have a chance to drop blaze rods.
		# Default: true
		"Blazes From Spawners Drop Blaze Rods" = true
		# The maximum number of banners that can spawn in a single small Nether dungeon.
		# Default: 2
		#Range: 0 ~ 8
		"Small Nether Dungeon Max Banner Count" = 2

