#Textures not included, make your own textures by making a resource pack that adds guard_steve_0 - 6
"Have guards use the steve model?" = false
"Have baby villagers have big heads like in bedrock?" = true

