
#Aether: Lost Content Client Configuration
[Visuals]
	#
	# Gives Valkyries halos, as they had in Aether Legacy.
	#
	# Default: false
	valkyrie_halos = false
	#
	# Gives the Valkyrie Queen a halo, as in Aether Legacy.
	#
	# Default: false
	valkyrie_queen_halo = false
	#
	# Gives the otherwise lifeless Aerwhales animation.
	# This brings them more in-line with the Aerwhale King, preventing them from standing out.
	#
	# Default: true
	updated_aerwhale_animations = true
	#
	# Plays dynamic boss music during the fight with the Aerwhale King.
	# Default: true
	aerwhale_king_boss_music = true
	#
	# Modifies how mountable Aether mobs feel while riding to resemble different versions of the mod. This has no effect on gameplay.
	#
	# NONE: Stiff rotation, exactly matching the rider. This is what Minecraft, and Aether use normally.
	# CLASSIC: Smooth, but loose feeling. Mounts will also turn in the direction you strafe in, otherwise staying close to where you're looking. This is how mounts were in original versions of the Aether.
	# LEGACY: Snappy, but not as stiff feeling movement. Close to how NONE works, but mounts will adopt a "drifting" pose while strafing, moving their heads to the opposite direction of travel. This is how mounts controlled in Aether Legacy.
	# SMOOTH_LEGACY: A best of both worlds solution. This combines the drifting pose of LEGACY, and the loose feeling of CLASSIC. This is an all new type of rotation.
	#
	# Default: CLASSIC
	#Allowed Values: NONE, CLASSIC, LEGACY, SMOOTH_LEGACY
	mount_rotation_type = "CLASSIC"
	#
	# How much FOV scales riding an Orange Moa as it gains speed.
	# Can be set to 0 to disable.
	#
	# Default: 10.0
	#Range: 0.0 ~ 60.0
	orange_moa_fov_scale = 10.0

