
[rendering]
	#
	# Displays info on top of Structure Blocks and Jigsaws in world.
	# Default: true
	show_structure_block_info = true
	#
	# Makes the render used by the Building Tool operate in a threaded context.
	# Default: true
	thread_building_tool = true

