[leaf_settings]
	#Modifies the size of the leaves
	# Default: 4
	# Range: 1 ~ 20
	leafSize = 4
	#Modifies how long it takes for the leaves to disappear.
	#In Ticks
	#Values over 2000 are not recommend
	# Default: 200
	# Range: > 100
	leafLifespan = 200
	#Modifies the amount of leaves that are spawning.
	#Values over 10000 are not recommend
	# Default: 10
	# Range: > 0
	leafSpawnRate = 10
	#Modifies the amount of leaves are spawning from conifer trees
	#Values over 10000 are not recommend
	# Default: 2
	# Range: > 0
	coniferLeafSpawnRate = 2
	#Whether player placed blocks should also drop leaves
	dropFromPlayerPlacedBlocks = true
	#How much room below the leaves block is needed for the leaves to spawn
	# Default: 1
	# Range: 1 ~ 20
	minimumFreeSpaceBelow = 1
	#How many leaves should spawn when a leaves block is decaying
	#This is the maximum amount, but they are binomial distributed.
	#This only works in singleplayer
	# Default: 10
	# Range: 1 ~ 1000
	decayingLeaves = 10

[wind]
	#Disable wind effects
	disableWind = false
	#Windless dimensions
	#By level registry name
	windlessDimension = ["minecraft:the_nether", "minecraft:the_end"]

[snow]
	#Disable snow particles
	disableSnow = false
	#Modifies the amount of snow that is spawning.
	#Values over 10000 are not recommend
	# Default: 10
	# Range: > 0
	snowSpawnRate = 10
	#How many snow particles should spawn when a snow block is decaying
	#This is the maximum amount, but they are binomial distributed.
	#This only works in singleplayer
	# Default: 40
	# Range: 1 ~ 1000
	decayingSnow = 40

[serene_seasons]
	#Disable the seasonal modifier when serene season is installed
	disableSeasonalModifier = false
	#Spring spawn rate modifier.
	#This modified is multiplied to the default spawn rate.
	# Default: 0.0
	# Range: 0.0 ~ 5.0
	spring = 0.0
	#Summer spawn rate modifier.
	#This modifier is multiplied to the default spawn rate.
	# Default: 0.2
	# Range: 0.0 ~ 5.0
	summer = 0.2
	#Autumn spawn rate modifier.
	#This modifier is multiplied to the default spawn rate.
	# Default: 1.0
	# Range: 0.0 ~ 5.0
	autumn = 1.0
	#Winter spawn rate modifier.
	#This modifier is multiplied to the default spawn rate.
	# Default: 0.3
	# Range: 0.0 ~ 5.0
	winter = 0.3
	#[Deprecated] spawnrate modifier per season/subseason
	#Format: '<season>:<modifier>'; eg 'SUMMER:0.23'
	#Subseasons override seasons
	#Allowed seasons: SPRING,SUMMER,AUTUMN,WINTER,EARLY_SPRING,MID_SPRING,LATE_SPRING,EARLY_SUMMER,MID_SUMMER,LATE_SUMMER,EARLY_AUTUMN,MID_AUTUMN,LATE_AUTUMN,EARLY_WINTER,MID_WINTER,LATE_WINTER
	seasonFallRate = []

	#Specify sub season modifier.
	#These Modifier are multiplied with the season modifier.
	[serene_seasons.subseasons]
		#Early Spring spawn rate modifier.
		#This modified is multiplied to the season spawn rate.
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		early_spring = 1.0
		#Mid Spring spawn rate modifier.
		#This modified is multiplied to the season spawn rate.
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		mid_spring = 1.0
		#Late Spring spawn rate modifier.
		#This modified is multiplied to the season spawn rate.
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		late_spring = 1.0
		#Early Summer spawn rate modifier.
		#This modified is multiplied to the season spawn rate.
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		early_summer = 1.0
		#Mid Summer spawn rate modifier.
		#This modified is multiplied to the season spawn rate.
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		mid_summer = 1.0
		#Late Summer spawn rate modifier.
		#This modified is multiplied to the season spawn rate.
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		late_summer = 1.0
		#Early Autumn spawn rate modifier.
		#This modified is multiplied to the season spawn rate.
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		early_autumn = 1.0
		#Mid Autumn spawn rate modifier.
		#This modified is multiplied to the season spawn rate.
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		mid_autumn = 1.0
		#Late Autumn spawn rate modifier.
		#This modified is multiplied to the season spawn rate.
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		late_autumn = 1.0
		#Early Winter spawn rate modifier.
		#This modified is multiplied to the season spawn rate.
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		early_winter = 1.0
		#Mid Winter spawn rate modifier.
		#This modified is multiplied to the season spawn rate.
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		mid_winter = 1.0
		#Late Winter spawn rate modifier.
		#This modified is multiplied to the season spawn rate.
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		late_winter = 1.0
