
[inventory]
	#Range: 0 ~ 54
	sneakShowAmount = 54
	#Range: 0 ~ 54
	normalShowAmount = 9
	#Range: 1 ~ 18
	showItemPreLine = 9
	blacklist = ["refinedstorage:disk_drive"]
	bypassLockedContainer = false

[customContainerName]
	onlyShowVanilla = false
	blacklist = ["thermal"]

