#The vertical offset for rendering the totem on the player.
#Range: -100.0 ~ 100.0
yOffset = 0.0
#The horizontal offset for rendering the totem on the player.
#Range: -100.0 ~ 100.0
xOffset = 0.0
#If enabled, renders the equipped totem on players.
renderTotem = true

