name: Bug Report
description: Create a bug report to help us improve Better Minecraft
labels: [ "bug" ]
body:
    -   type: textarea
        attributes:
            label: Describe the Bug
            description: A clear and concise description of what the bug is
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Reproduction Steps
            description: Tell us about the steps to reproduce the bug
            value: |
                1.
                2.
                3.
                ...
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Screenshots and Videos
            description: If applicable, add screenshots or videos to help explain your problem
        validations:
            required: false
    -   type: input
        attributes:
            label: Crash Report or Log
            description: If applicable, please add a **link** to the crash report or log that was created when this issue occured. You can upload the crash report to a site like Pastebin or GitHub Gist. Please **do not** paste the whole crash report in this issue
        validations:
            required: false
    -   type: input
        attributes:
            label: Operating System
            description: The operating system you were using when the bug occured
            placeholder: Windows 11
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Minecraft Version
            description: The version of Minecraft you were using when the bug occured
            options:
                - "1.16.5"
                - "1.18.2"
                - "1.19.2"
                - "1.20.1"
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Modloader
            description: The modloader you were using when the bug occured
            options:
                - "Forge"
                - "Fabric"
        validations:
            required: true
    -   type: input
        attributes:
            label: Modpack Version
            description: The modpack version you were using when the bug occured (such as v26, v3, etc)
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Other Mods
            description: Any additional mods you added to the modpack
        validations:
            required: false
    -   type: markdown
        attributes:
            value: "Thank you for taking the time to make this bug report and to help improve Better Minecraft"
