#Info background transparency. 1 means opaque.
#Range: 0.0 ~ 1.0
infoAlpha = 0.5
#Info alignment. 0 means top. 1 means middle. 2 means bottom.
#Range: 0 ~ 2
infoAnchor = 1
#Info max width. 0.5 means half screen. default: 0.3
#Range: 0.0 ~ 0.5
infoMaxWidth = 0.3
#Scroll sensitivity
#Range: 0.01 ~ 10000.0
scrollTick = 1.0
#Render Selection only when pressing shift
selectionDisplayRequireShift = false
#Scroll for selection only when pressing shift
selectionScrollRequireShift = true

