#.
#Client Settings
[client]
	#.
	#Whether lantern accessories should switch to the left side or not.
	"Left-Handed Lanterns" = false
	#.
	#Whether lantern accessories should switch to the back of the player or not.
	"Back Lanterns" = false
	#.
	#No performance impact, just cosmetic.
	"Enable Lantern Swinging Physics" = true
	#.
	#How affected by in-world forces lantern physics should be. Default 1f
	# Default: 1.0
	# Range: 0.10000000149011612 ~ 10.0
	"Lantern Bounciness" = 1.0
