#If enabled, players automatically attempt to use sleeping bags when placed.
autoUse = true
#If enabled, players cannot sleep again for a period of time after sleeping.
restrictSleeping = false
#If restrictSleeping is true, this value will determine the length of wait time (larger numbers sleep sooner).
#Range: 1.0 ~ 20.0
restMultiplier = 2.0
#The time of day that hammocks can be used.
#Allowed Values: NONE, DAY, NIGHT, DAY_OR_NIGHT
hammockUse = "DAY"
#The time of day that sleeping bags can be used.
#Allowed Values: NONE, DAY, NIGHT, DAY_OR_NIGHT
sleepingBagUse = "NIGHT"
#The percentage chance that a sleeping bag will break upon use.
#Range: 0 ~ 100
sleepingBagBreakChance = 0
#The value that will be multiplied by a player's luck then added to sleepingBagBreakChance.
#Range: -1.0 ~ 1.0
sleepingBagBreakChanceLuckMultiplier = 0.0
#The status effects to apply to players after using the sleeping bag.
#Format: effect;duration(secs);power
sleepingBagEffects = []

