#General settings
general = {}

#Generation settings
[generation_settings]
	#The size of aether biome regions from each mod that uses AeroBlender.
	#Range: 2-6
	aether_region_size = 2
	#The weighting of vanilla biome regions in the aether.
	#Range: 0-2147483647
	vanilla_aether_region_weight = 10

