# The configuration file for Log Begone

[logbegone]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = ["the_aether", "########## GL ERROR ##########", "@ Pre render", "65539: Invalid key -1", "@ Render"]

# If a log message matches one of these regex patterns, it will be filtered out from logging. EX:
regex = []