enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
universal_ores = true
everycomp = true
edenring = true
farmersdelight = true
bountiful = true
barteringstation = true
nears = true
chubbystuff = true
wondrouswilds = true
oxidized = true
betternether = true
galosphere = true
variantcraftingtables = true
betterend = true
another_furniture = true
friendsandfoes = true
twigs = true
ecologics = true
comforts = true
snowyspirit = true
duckling = true
yigd = true
nethersdelight = true
byg = true
the_bumblezone = true
handcrafted = true
ftbquests = true
snowrealmagic = true
creatures_from_the_snow = true
sod = true
charm = true
customportalapi = true
naturalist = true
supplementaries = true
magnumtorch = true
winterly = true
deeperdarker = true
quartzelv = true
terrestria = true
culturaldelights = true
biomemakeover = true
geodes = true
windchimes = true
spirit = true
seasons = true
goodall = true
woof = true
rottencreatures = true
plushies = true
minecraft = true
architects_palette = true
farmersrespite = true
fwaystones = true
endgoblintraders = true
immersive_weathering = true
twilightforest = true
voidz = true
dragonloot = true
bosses_of_mass_destruction = true
adventurez = true
decorative_blocks = true
tradingpost = true
paradise_lost = true
vinery = true
gofish = true
toms_storage = true
expandeddelight = true
netherdepthsupgrade = true
