["Vanilla Changes"]
	"Allow healing and Regeneration arrows to not do damage?" = true
	#Weig
	#ht is calculated by dividing the current value by the sum of all weights combined.
	#Use https://minecraft.fandom.com/wiki/Bastion_Remnant?so=search#cite_ref-piglin_group_1-39 as a guide.
	#The default weight for alchemists spawning is 4, giving them a 28% chance of spawning in bastions.
	#(Due to this, regular piglins have a spawn rate of 28% aswell, and brutes have a spawn rate of 7% spawn rate, changed values will have to account for this).
	#To change the natural spawn rates, use a datapack that overrides add_alchemist.json file, located in data/piglinproliferation/data/forge/biome_modifier
	#Range: > -2147483648
	"Alchemist spawnrate weight in bastions" = 4
	#Range: 0.0 ~ 9000.0
	"Chance of zombified piglins spawning with crossbows" = 0.5
	#Range: 0.0 ~ 9000.0
	"Chance of zombified piglins spawning with regular piglin clothing" = 0.8999999761581421
	#Range: 0.0 ~ 9000.0
	"Chance of zombified piglins spawning with brute clothing (including items)" = 0.014999999664723873
	#Range: 0.0 ~ 9000.0
	"Chance of zombified piglins spawning with alchemist clothing (including items)" = 0.10000000149011612
	#Range: 0.0 ~ 9000.0
	"Chance of zombified piglins spawning with traveler clothing " = 0.10000000149011612

[Buckler]
	"Mobs that can also use the buckler" = ["guardvillagers:guard"]
	"Have the explosion spawned while using the Bang! enchant destroy blocks?" = false
	"Have brutes spawn with bucklers?" = true
	#Range: > -2147483648
	"How long should the buckler's cooldown be in ticks?" = 240
	#Range: > -2147483648
	"How long should the buckler's charge move be in ticks?" = 15
	#Range: > -2147483648
	"How long should the buckler's charge move if you have the max level of turning enchant be in ticks?" = 40
	#Range: 0.0 ~ 9999999.0
	"Chance of buckler appearing in bastion loot" = 0.25
	#Experimental: Bucklers enchanted with Turning will allow the player to launch off of blocks they collide with.
	#Range: 0.0 ~ 999999.0
	"Launch strength " = 0.15

["Piglin Alchemist"]
	#Range: 0.0 ~ 9000.0
	"Chance of alchemist potions not getting broken when killed" = 0.20000000298023224

	["Piglin Alchemist"."Healing Arrow Chances"]
		#Range: 0.0 ~ 100.0
		"Chances of an alchemist getting healing arrows" = 0.30000001192092896
		#Range: > -2147483648
		"Minmium healing arrow stack size" = 1
		#Range: > -2147483648
		"Maximium healing arrow stack size" = 6

["Piglin Traveler"]
	#Range: 0.0 ~ 9000.0
	"Chance of travelers equipping crossbows" = 0.20000000298023224
