
["Config category"]
	#Delay before a chunk is saved to disk, default: 300 seconds. If you enable the noSaveAll config, it is suggest to set this to 180.
	#Range: 100 ~ 3000
	chunkSaveDelay = 300
	#Enables debug logging of how many chunks got saved in a tick. default: false
	debugLogging = false

