[Advancements]
	#Filter advancements when Charmony-mod features or settings are disabled.
	#Disabling this feature will cause unexpected behavior and potentially unachievable advancements.
	"Advancements enabled" = true

[ColoredGlints]
	#Customizable item enchantment colors.
	#This feature is a helper for other Charmony mods. If disabled then other mods that rely on it will not function properly.
	"ColoredGlints enabled" = true
	#Overrides the default enchantment glint color.
	#Must be a valid dye color name.
	"Default glint color" = "purple"

[Diagnostics]
	#Enable debugging mode. Produces more logging output and adds some testing code.
	"Debug mode" = false
	#Enable mixin compatibility mode. All Charmony mixins will be disabled, making Charmony mods useless.
	#Use this if any Charmony mods are crashing to determine if there is a mixin collision with another mod.
	"Compat mode" = false

[Recipes]
	#Filter recipes when Charmony-mod features or settings are disabled.
	#Disabling this feature will cause unexpected behavior and potentially unachievable recipes.
	"Recipes enabled" = true

[VariantWood]
	#Variant wood features such as barrels, chests and ladders.
	"VariantWood enabled" = true
	#If true, enables barrels made from different kinds of wood.
	"Variant barrels" = true
	#If true, enables bookshelves made from different kinds of wood.
	"Variant bookshelves" = true
	#If true, enables chests made from different kinds of wood.
	"Variant chests" = true
	#If true, enables chiseled bookshelves made from different kinds of wood.
	"Variant chiseled bookshelves" = true
	#If true, enables ladders made from different kinds of wood.
	"Variant ladders" = true
