ADD_END_CITY_TREASURE = true
BLACKLISTED_DIMENSIONS = []
DISPLAY_TOTEM_ON_CHEST = true
GIVE_TOTEM_EFFECTS = true
IS_INVERTED_BLACKLIST = false
NEEDS_TOTEM = true
SHOW_TOTEM_TOOLTIP = false
TELEPORT_HEIGHT_OFFSET = 64
USE_TOTEM_FROM_INVENTORY = false
